### ISSUE TITLE
Plugin Error: NoClassDefFoundError

### ISSUE THREAD

**Issue by tiann** [pengwei1024/AndroidSourceViewer#5]
> 下午7:10	Plugin Error: AndroidSourceViewer threw an uncaught NoClassDefFoundError. Disable Plugin

> 下午7:10	NoClassDefFoundError: android/text/TextUtils

Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Mac OSX 10.11.6  查看Activity源码。

**Comment by tiann** [comment]
我知道了，鼠标光标要在一个合法的类上面。建议其他的时候隐藏菜单。

**Comment by tiann** [comment]
还是不行，菜单出来之后选择一个版本，还是报同样的错误。

**Comment by tiann** [comment]
`android/text/TextUtils
java.lang.NoClassDefFoundError: android/text/TextUtils
	at com.apkfuns.androidsourceviewer.util.NotificationUtils$1.run(NotificationUtils.java:31)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:291)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by pengwei1024** [comment]
多谢反馈，才发现我居然用了TextUtils类。。。麻烦再试试行不行
[AndroidSourceViewer-1.0.1.jar.zip](https://github.com/pengwei1024/AndroidSourceViewer/files/1478333/AndroidSourceViewer-1.0.1.jar.zip)

**Comment by tiann** [comment]
@pengwei1024 可以了 👍  不过貌似AndroidXref搞挂了，不会是你的这个插件的流量带来的吧。。
好东西，加油！

**Comment by tiann** [comment]
@pengwei1024 可否直接用官网的数据？https://android.googlesource.com/platform/art/+/android-7.0.0_r1/runtime/art_method.h 类似这样

**Comment by pengwei1024** [comment]
可以试试![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/50/pcmoren_huaixiao_thumb.png)，我用服务器代理一下 [https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r34/core/java/android/app/Activity.java](https://android.googlesource.com/platform/frameworks/base/+/android-8.0.0_r34/core/java/android/app/Activity.java)

**Comment by pengwei1024** [comment]
新更新的1.0.2已经支持 android.googlesource.com 下载，以后AndroidXref 挂了也没事了，感谢你的建议 [https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar](https://github.com/pengwei1024/AndroidSourceViewer/tree/master/jar)
